#!/bin/zsh
S="${TW_DOCS_DIR:?set TW_DOCS_DIR to the scrape output dir}"
B="$HOME/.claude/skills/gstack/browse/dist/browse"
SKIP="installation editor-setup compatibility upgrade-guide styling-with-utility-classes hover-focus-and-other-states responsive-design dark-mode theme colors adding-custom-styles detecting-classes-in-source-files functions-and-directives preflight"
PAGES="accent-color align-content align-items align-self animation appearance aspect-ratio backdrop-filter backdrop-filter-blur backdrop-filter-brightness backdrop-filter-contrast backdrop-filter-grayscale backdrop-filter-hue-rotate backdrop-filter-invert backdrop-filter-opacity backdrop-filter-saturate backdrop-filter-sepia backface-visibility background-attachment background-blend-mode background-clip background-color background-image background-origin background-position background-repeat background-size block-size border-collapse border-color border-radius border-spacing border-style border-width box-decoration-break box-shadow box-sizing break-after break-before break-inside caption-side caret-color clear color color-scheme columns content cursor display field-sizing fill filter filter-blur filter-brightness filter-contrast filter-drop-shadow filter-grayscale filter-hue-rotate filter-invert filter-saturate filter-sepia flex flex-basis flex-direction flex-grow flex-shrink flex-wrap float font-family font-feature-settings font-size font-smoothing font-stretch font-style font-variant-numeric font-weight forced-color-adjust gap grid-auto-columns grid-auto-flow grid-auto-rows grid-column grid-row grid-template-columns grid-template-rows height hyphens inline-size isolation justify-content justify-items justify-self letter-spacing line-clamp line-height list-style-image list-style-position list-style-type margin mask-clip mask-composite mask-image mask-mode mask-origin mask-position mask-repeat mask-size mask-type max-block-size max-height max-inline-size max-width min-block-size min-height min-inline-size min-width mix-blend-mode object-fit object-position opacity order outline-color outline-offset outline-style outline-width overflow overflow-wrap overscroll-behavior padding perspective perspective-origin place-content place-items place-self pointer-events position resize rotate scale scroll-behavior scroll-margin scroll-padding scroll-snap-align scroll-snap-stop scroll-snap-type scrollbar-color scrollbar-gutter scrollbar-width skew stroke stroke-width tab-size table-layout text-align text-decoration-color text-decoration-line text-decoration-style text-decoration-thickness text-indent text-overflow text-shadow text-transform text-underline-offset text-wrap top-right-bottom-left touch-action transform transform-origin transform-style transition-behavior transition-delay transition-duration transition-property transition-timing-function translate user-select vertical-align visibility white-space width will-change word-break z-index zoom"
n=0
for p in ${=PAGES}; do
  out="$S/$p.json"
  [ -s "$out" ] && continue
  $B goto "https://tailwindcss.com/docs/$p" >/dev/null 2>&1
  $B eval "$(dirname "$0")/extract.js" 2>/dev/null | sed -e '/^--- BEGIN/d' -e '/^--- END/d' > "$out.tmp"
  if python3 -c "import json,sys; json.load(open('$out.tmp'))" 2>/dev/null; then mv "$out.tmp" "$out"; n=$((n+1)); else echo "FAIL $p"; rm -f "$out.tmp"; fi
done
echo "scraped $n; total $(ls $S/*.json | wc -l)"
