//! tw — Tailwind class-string → gpui [`StyleRefinement`] parser.
//!
//! `parse(theme, "flex h-9 px-2.5 bg-primary hover:bg-primary/80")` resolves a
//! Tailwind class string into per-state [`StyleRefinement`] buckets (base,
//! hover, focus, focus-visible, active, disabled) that plug directly into
//! gpui's state-style hooks (`hover()`, `focus_visible()`, `active()` all take
//! `FnOnce(StyleRefinement) -> StyleRefinement`). Because every rcn component
//! implements [`Styled`] (the className-passthrough convention), the extension
//! traits at the bottom deliver a whole class string to any component in one
//! call.
//!
//! ## Registry layout
//!
//! Utilities are implemented in per-family modules mirroring the Tailwind docs
//! chapters (`layout`, `flex_grid`, `spacing`, `sizing`, `typography`,
//! `backgrounds`, `borders`, `effects`, `transforms`, `interactivity`), each
//! registered in [`HANDLERS`] and carrying its own unit tests. What a family
//! does not claim falls through to the coverage ledger ([`coverage`]): every
//! utility root from the canonical Tailwind manifest (`manifest.json`,
//! generated by `scripts/pull-tailwind.py`) is classified there as
//! `Supported`, `Todo`, or `NoEquivalent(reason)`. `NoEquivalent` tokens are
//! reported in [`TwStyles::skipped`]; everything else unhandled lands in
//! [`TwStyles::unknown`]. Enforcement tests in `coverage` keep the ledger and
//! the handlers in lockstep.
//!
//! ## Deliberate deviations from real Tailwind/CSS
//!
//! - **Order-sensitive**: later classes in the string win over earlier ones
//!   for the same property (like `tailwind-merge`, unlike raw CSS selector
//!   specificity). `dark:` and state variants therefore belong *after* the
//!   classes they override, which is how shadcn's cva strings are written.
//! - **`dark:` resolves at parse time** against `theme.dark` — the token is
//!   applied or dropped, not kept as a runtime condition.
//! - **`ring-*` synthesizes a box shadow** (zero blur, spread = ring width),
//!   appended to the bucket's `box_shadow`, matching `motion::focus_ring`.
//! - **`translate-x/y-*` map to `left`/`top` insets** — gpui has no
//!   transforms. The element needs `relative` for the offset to take effect.
//! - **Logical properties assume LTR**: `ps`/`ms`/`start`/`border-s`/
//!   `rounded-ss` map to their left/physical equivalents.
//! - **No transitions/animations**: state changes are instant in gpui; motion
//!   timings live in `crate::motion`.

mod backgrounds;
mod borders;
mod coverage;
mod effects;
mod flex_grid;
mod interactivity;
mod layout;
mod palette;
mod sizing;
mod spacing;
mod transforms;
mod typography;

use std::collections::HashMap;
use std::sync::OnceLock;

use gpui::{
    BoxShadow, Hsla, InteractiveElement, Length, Pixels, Refineable as _,
    StatefulInteractiveElement, StyleRefinement, Styled, point, px, relative,
};

use crate::theme::{Theme, alpha};

/// Parsed class string: one refinement per interaction state.
#[derive(Default, Debug)]
pub struct TwStyles {
    pub base: StyleRefinement,
    pub hover: Option<StyleRefinement>,
    pub focus: Option<StyleRefinement>,
    pub focus_visible: Option<StyleRefinement>,
    pub active: Option<StyleRefinement>,
    pub disabled: Option<StyleRefinement>,
    /// Real Tailwind utilities with no gpui equivalent (dropped; the coverage
    /// ledger records why).
    pub skipped: Vec<String>,
    /// Tokens the parser does not handle: typos, or `Todo` utilities the
    /// registry has not implemented yet.
    pub unknown: Vec<String>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Bucket {
    Base = 0,
    Hover = 1,
    Focus = 2,
    FocusVisible = 3,
    Active = 4,
    Disabled = 5,
}

/// `ring-*` accumulates width + color separately (like CSS custom props
/// `--tw-ring-*`), then [`parse`] synthesizes one box shadow per bucket.
#[derive(Default, Clone, Copy)]
pub(super) struct RingState {
    pub width: Option<Pixels>,
    pub color: Option<Hsla>,
}

/// Per-token context handed to family handlers.
pub(super) struct Ctx<'a> {
    pub theme: &'a Theme,
    pub ring: &'a mut RingState,
    /// -1.0 when the token had a leading `-` (negative margins/insets).
    pub sign: f32,
}

/// A family handler: apply `t` (variant prefixes and leading `-` stripped) to
/// the refinement. Returns `(refined, true)` when the token was applied, or
/// `(unchanged, false)` to let the next family (and finally the coverage
/// ledger) look at it.
type Handler = fn(StyleRefinement, &str, &mut Ctx) -> (StyleRefinement, bool);

/// The utility registry, tried in order. Order resolves prefix ambiguity:
/// e.g. `border-*` must reach `borders` before any generic color fallback.
const HANDLERS: &[Handler] = &[
    layout::apply,
    flex_grid::apply,
    spacing::apply,
    sizing::apply,
    typography::apply,
    backgrounds::apply,
    borders::apply,
    effects::apply,
    transforms::apply,
    interactivity::apply,
];

/// Parse a Tailwind class string into per-state style refinements.
pub fn parse(theme: &Theme, classes: &str) -> TwStyles {
    let mut out = TwStyles::default();
    let mut rings = [RingState::default(); 6];

    for token in classes.split_whitespace() {
        let mut bucket = Bucket::Base;
        let mut dark_only = false;
        let mut known_prefixes = true;
        let mut rest = token;
        while let Some((prefix, tail)) = rest.split_once(':') {
            match prefix {
                "dark" => dark_only = true,
                "hover" => bucket = Bucket::Hover,
                "focus" => bucket = Bucket::Focus,
                "focus-visible" => bucket = Bucket::FocusVisible,
                "active" => bucket = Bucket::Active,
                "disabled" => bucket = Bucket::Disabled,
                // `[a]:`, `group-hover:`, `aria-invalid:`, `sm:`, …
                _ => known_prefixes = false,
            }
            rest = tail;
        }
        if !known_prefixes {
            out.skipped.push(token.to_string());
            continue;
        }
        if dark_only && !theme.dark {
            continue;
        }

        let (t, neg) = match rest.strip_prefix('-') {
            Some(r) => (r, true),
            None => (rest, false),
        };
        let mut ctx = Ctx {
            theme,
            ring: &mut rings[bucket as usize],
            sign: if neg { -1. } else { 1. },
        };

        let slot = bucket_mut(&mut out, bucket);
        let mut s = std::mem::take(slot);
        let mut applied = false;
        for handler in HANDLERS {
            let (next, done) = handler(s, t, &mut ctx);
            s = next;
            if done {
                applied = true;
                break;
            }
        }
        *slot = s;
        if !applied {
            match coverage::lookup(t) {
                Some(coverage::Status::NoEquivalent(_)) => out.skipped.push(token.to_string()),
                _ => out.unknown.push(token.to_string()),
            }
        }
    }

    for bucket in [
        Bucket::Base,
        Bucket::Hover,
        Bucket::Focus,
        Bucket::FocusVisible,
        Bucket::Active,
        Bucket::Disabled,
    ] {
        let ring = rings[bucket as usize];
        if ring.width.is_none() && ring.color.is_none() {
            continue;
        }
        let shadow = BoxShadow {
            // Tailwind's default ring is currentColor; shadcn always names a
            // color, so default to the theme ring at 50% like `ring-ring/50`.
            color: ring.color.unwrap_or(alpha(theme.ring, 0.5)),
            offset: point(px(0.), px(0.)),
            blur_radius: px(0.),
            spread_radius: ring.width.unwrap_or(px(1.)),
            inset: false,
        };
        let slot = bucket_mut(&mut out, bucket);
        match &mut slot.box_shadow {
            Some(shadows) => shadows.push(shadow),
            None => slot.box_shadow = Some(vec![shadow]),
        }
    }

    out
}

fn bucket_mut(out: &mut TwStyles, bucket: Bucket) -> &mut StyleRefinement {
    match bucket {
        Bucket::Base => &mut out.base,
        Bucket::Hover => out.hover.get_or_insert_default(),
        Bucket::Focus => out.focus.get_or_insert_default(),
        Bucket::FocusVisible => out.focus_visible.get_or_insert_default(),
        Bucket::Active => out.active.get_or_insert_default(),
        Bucket::Disabled => out.disabled.get_or_insert_default(),
    }
}

// ---------------------------------------------------------------------------
// Shared value parsers
// ---------------------------------------------------------------------------

/// Tailwind length: `2.5` → 10px (4px scale), `px` → 1px, `[Npx]`/`[Nrem]`
/// arbitrary values.
pub(super) fn scale_px(v: &str) -> Option<Pixels> {
    if v == "px" {
        return Some(px(1.));
    }
    if let Some(inner) = v.strip_prefix('[').and_then(|x| x.strip_suffix(']')) {
        if let Some(n) = inner.strip_suffix("px") {
            return n.parse::<f32>().ok().map(px);
        }
        if let Some(n) = inner.strip_suffix("rem") {
            return n.parse::<f32>().ok().map(|r| px(r * 16.));
        }
        return None;
    }
    v.parse::<f32>().ok().map(|n| px(n * 4.))
}

/// Length values for sizing/inset roots: everything [`scale_px`] accepts,
/// plus `full`, fractions (`1/2` → 50%), and `auto`.
pub(super) fn scale_len(v: &str) -> Option<Length> {
    match v {
        "auto" => return Some(Length::Auto),
        "full" => return Some(relative(1.).into()),
        _ => {}
    }
    if let Some((num, den)) = v.split_once('/')
        && let (Ok(n), Ok(d)) = (num.parse::<f32>(), den.parse::<f32>())
        && d != 0.
    {
        return Some(relative(n / d).into());
    }
    scale_px(v).map(Into::into)
}

/// Resolve `primary`, `red-500`, `muted-foreground/50`, `[#323232]`, … —
/// theme tokens first, then the generated default palette, then arbitrary
/// hex. `/NN` suffixes apply alpha.
pub(super) fn color(theme: &Theme, spec: &str) -> Option<Hsla> {
    let (name, alpha_pct) = match spec.rsplit_once('/') {
        Some((n, a)) => (n, Some(a)),
        None => (spec, None),
    };
    let base: Hsla = if let Some(inner) = name.strip_prefix('[').and_then(|x| x.strip_suffix(']')) {
        let hex = inner.strip_prefix('#')?;
        if hex.len() != 6 {
            return None;
        }
        gpui::rgb(u32::from_str_radix(hex, 16).ok()?).into()
    } else if let Some(token) = theme_token(theme, name) {
        token
    } else {
        match name {
            "transparent" => gpui::transparent_black(),
            _ => palette::palette(name)?,
        }
    };
    match alpha_pct {
        Some(a) => Some(alpha(base, a.parse::<f32>().ok()? / 100.)),
        None => Some(base),
    }
}

/// rcn's semantic theme tokens (shadcn CSS-variable names).
fn theme_token(theme: &Theme, name: &str) -> Option<Hsla> {
    Some(match name {
        "background" => theme.background,
        "foreground" => theme.foreground,
        "card" => theme.card,
        "card-foreground" => theme.card_foreground,
        "popover" => theme.popover,
        "popover-foreground" => theme.popover_foreground,
        "primary" => theme.primary,
        "primary-foreground" => theme.primary_foreground,
        "secondary" => theme.secondary,
        "secondary-foreground" => theme.secondary_foreground,
        "muted" => theme.muted,
        "muted-foreground" => theme.muted_foreground,
        "accent" => theme.accent,
        "accent-foreground" => theme.accent_foreground,
        "destructive" => theme.destructive,
        "destructive-foreground" => theme.destructive_foreground,
        "border" => theme.border,
        "input" => theme.input,
        "ring" => theme.ring,
        _ => return None,
    })
}

/// Radius values: the theme-mapped scale, fixed upper scale, `full`/`none`,
/// `[Npx]`, and shadcn's `[min(var(--radius-SCALE),Npx)]` clamp.
pub(super) fn radius(theme: &Theme, v: &str) -> Option<Pixels> {
    Some(match v {
        "none" => px(0.),
        "xs" => px(2.),
        "sm" => theme.radius_sm(),
        "md" => theme.radius_md(),
        "lg" => theme.radius_lg(),
        "xl" => theme.radius_xl(),
        "2xl" => px(16.),
        "3xl" => px(24.),
        "4xl" => px(32.),
        "full" => px(9999.),
        _ => return arbitrary_radius(theme, v),
    })
}

fn arbitrary_radius(theme: &Theme, v: &str) -> Option<Pixels> {
    let inner = v.strip_prefix('[')?.strip_suffix(']')?;
    if let Some(n) = inner.strip_suffix("px") {
        return n.parse::<f32>().ok().map(px);
    }
    let rest = inner.strip_prefix("min(var(--radius-")?;
    let (scale, tail) = rest.split_once(')')?;
    let cap: f32 = tail.strip_prefix(',')?.strip_suffix("px)")?.parse().ok()?;
    let base = match scale {
        "sm" => theme.radius_sm(),
        "md" => theme.radius_md(),
        "lg" => theme.radius_lg(),
        "xl" => theme.radius_xl(),
        _ => return None,
    };
    Some(base.min(px(cap)))
}

// ---------------------------------------------------------------------------
// Coverage-ledger lookup (longest matching root)
// ---------------------------------------------------------------------------

static LEDGER_MAP: OnceLock<HashMap<&'static str, &'static coverage::Entry>> = OnceLock::new();

fn ledger_map() -> &'static HashMap<&'static str, &'static coverage::Entry> {
    LEDGER_MAP.get_or_init(|| coverage::LEDGER.iter().map(|e| (e.name, e)).collect())
}

// ---------------------------------------------------------------------------
// Application to elements
// ---------------------------------------------------------------------------

/// Apply only the base bucket — for plain [`Styled`] elements (and nested
/// refinements) with no interaction states in the class string. Unknown
/// tokens are ignored here (parse yourself to see diagnostics).
#[allow(dead_code)] // public parser surface; components adopt incrementally
pub trait TwStyledExt: Styled + Sized {
    fn tw_base(mut self, theme: &Theme, classes: &str) -> Self {
        let styles = parse(theme, classes);
        self.style().refine(&styles.base);
        self
    }
}

impl<T: Styled> TwStyledExt for T {}

fn apply_interactive<T: InteractiveElement + Styled>(mut el: T, styles: TwStyles) -> T {
    el.style().refine(&styles.base);
    let mut el = el;
    if let Some(hover) = styles.hover {
        el = el.hover(move |mut r| {
            r.refine(&hover);
            r
        });
    }
    if let Some(focus) = styles.focus {
        el = el.focus(move |mut r| {
            r.refine(&focus);
            r
        });
    }
    if let Some(focus_visible) = styles.focus_visible {
        el = el.focus_visible(move |mut r| {
            r.refine(&focus_visible);
            r
        });
    }
    el
}

/// Apply base + hover + focus + focus-visible buckets. `active:` needs a
/// stateful element — use [`TwStatefulExt::tw_stateful`] there.
pub trait TwInteractiveExt: InteractiveElement + Styled + Sized {
    fn tw(self, theme: &Theme, classes: &str) -> Self {
        let styles = parse(theme, classes);
        debug_assert!(
            styles.active.is_none() && styles.disabled.is_none(),
            "active:/disabled: classes need tw_stateful / component state"
        );
        apply_interactive(self, styles)
    }
}

impl<T: InteractiveElement + Styled> TwInteractiveExt for T {}

/// Apply every bucket except `disabled:` (a component-state concern — gate it
/// with `.when(disabled, …)` and the [`TwStyles::disabled`] refinement).
pub trait TwStatefulExt: StatefulInteractiveElement + Styled + Sized {
    fn tw_stateful(self, theme: &Theme, classes: &str) -> Self {
        let mut styles = parse(theme, classes);
        let active = styles.active.take();
        let mut el = apply_interactive(self, styles);
        if let Some(active) = active {
            el = el.active(move |mut r| {
                r.refine(&active);
                r
            });
        }
        el
    }
}

impl<T: StatefulInteractiveElement + Styled> TwStatefulExt for T {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::motion;
    use gpui::transparent_black;

    pub(crate) fn assert_style_eq(got: &StyleRefinement, expected: &StyleRefinement) {
        assert_eq!(format!("{got:?}"), format!("{expected:?}"));
    }

    #[test]
    fn layout_and_spacing() {
        let theme = Theme::light();
        let styles = parse(
            &theme,
            "flex items-center justify-center h-9 px-2.5 gap-1.5 top-px",
        );
        let expected = StyleRefinement::default()
            .flex()
            .items_center()
            .justify_center()
            .h(px(36.))
            .px(px(10.))
            .gap(px(6.))
            .top(px(1.));
        assert_style_eq(&styles.base, &expected);
        assert!(styles.unknown.is_empty() && styles.skipped.is_empty());
    }

    #[test]
    fn colors_alpha_and_hover_bucket() {
        let theme = Theme::light();
        let styles = parse(
            &theme,
            "bg-primary text-primary-foreground border-transparent hover:bg-primary/80",
        );
        let expected_base = StyleRefinement::default()
            .bg(theme.primary)
            .text_color(theme.primary_foreground)
            .border_color(transparent_black());
        assert_style_eq(&styles.base, &expected_base);
        let expected_hover = StyleRefinement::default().bg(alpha(theme.primary, 0.8));
        assert_style_eq(styles.hover.as_ref().unwrap(), &expected_hover);
    }

    #[test]
    fn palette_colors_resolve() {
        let theme = Theme::light();
        let styles = parse(&theme, "bg-blue-500 text-red-600/75 border-slate-200");
        assert!(styles.unknown.is_empty(), "unknown: {:?}", styles.unknown);
        assert!(styles.base.background.is_some());
        assert!(styles.base.text.color.is_some());
        assert!(styles.base.border_color.is_some());
    }

    #[test]
    fn dark_gating() {
        let classes = "bg-destructive/10 dark:bg-destructive/20";
        let light = parse(&Theme::light(), classes);
        let dark = parse(&Theme::dark(), classes);
        assert_style_eq(
            &light.base,
            &StyleRefinement::default().bg(alpha(Theme::light().destructive, 0.1)),
        );
        assert_style_eq(
            &dark.base,
            &StyleRefinement::default().bg(alpha(Theme::dark().destructive, 0.2)),
        );
    }

    #[test]
    fn ring_synthesis_matches_motion_focus_ring() {
        let theme = Theme::light();
        let styles = parse(
            &theme,
            "focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50",
        );
        let expected = StyleRefinement::default()
            .border_color(theme.ring)
            .shadow(motion::focus_ring(&theme));
        assert_style_eq(styles.focus_visible.as_ref().unwrap(), &expected);
    }

    #[test]
    fn arbitrary_values() {
        let theme = Theme::light();
        let styles = parse(
            &theme,
            "w-[137px] rounded-[min(var(--radius-md),8px)] bg-[#323232]",
        );
        let expected = StyleRefinement::default()
            .w(px(137.))
            .rounded(theme.radius_md().min(px(8.)))
            .bg(Hsla::from(gpui::rgb(0x323232)));
        assert_style_eq(&styles.base, &expected);
    }

    #[test]
    fn last_class_wins_like_tailwind_merge() {
        let theme = Theme::light();
        let styles = parse(&theme, "p-4 px-2");
        let expected = StyleRefinement::default().p(px(16.)).px(px(8.));
        assert_style_eq(&styles.base, &expected);
    }

    #[test]
    fn skipped_and_unknown_are_reported() {
        let theme = Theme::light();
        let styles = parse(
            &theme,
            "select-none underline-offset-4 transition-all [a]:hover:bg-muted totally-fake",
        );
        assert_eq!(
            styles.skipped,
            vec![
                "select-none",
                "underline-offset-4",
                "transition-all",
                "[a]:hover:bg-muted"
            ]
        );
        assert_eq!(styles.unknown, vec!["totally-fake"]);
    }

    #[test]
    fn negative_values() {
        let theme = Theme::light();
        let styles = parse(&theme, "-ml-px -translate-y-0.5");
        let expected = StyleRefinement::default().ml(px(-1.)).top(px(-2.));
        assert_style_eq(&styles.base, &expected);
    }

    #[test]
    fn fractions_resolve_to_relative_lengths() {
        let theme = Theme::light();
        let styles = parse(&theme, "w-1/2 h-full");
        let expected = StyleRefinement::default().w(relative(0.5)).h(relative(1.));
        assert_style_eq(&styles.base, &expected);
    }
}
