#!/usr/bin/env python3
"""Generate src/storybook_docs.rs from the component sources.

For every module in src/components/, extract each public type's builder
API (pub fn signatures + their /// docs) so the storybook can render an
API-reference table that can never drift from the code. Also extract each
`fn *_preview` body from src/storybook.rs as the usage snippet — the
storybook examples ARE the usage documentation.

Run from the repo root: python3 scripts/gen-docs.py
"""

import re
from pathlib import Path

COMPONENTS = Path("src/components")
STORYBOOK = Path("src/storybook.rs")
OUT = Path("src/storybook_docs.rs")


def extract_api(path: Path):
    """(type_name, [(signature, doc)]) entries for pub fns in pub impls."""
    text = path.read_text()
    entries = []
    current_type = None
    pending_doc: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        m = re.match(r"impl (?:\w+ for )?(\w+)", line)
        if m and " for " not in line:
            current_type = m.group(1)
            pending_doc = []
            continue
        if line.startswith("///"):
            pending_doc.append(line[3:].strip())
            continue
        m = re.match(r"pub(?:\(crate\))? fn (\w+)\s*(\(.*)", line)
        if m and current_type and not line.startswith("pub mod"):
            name = m.group(1)
            # Reconstruct a compact one-line signature up to the return arrow.
            sig = line
            sig = re.sub(r"\s*\{\s*$", "", sig)
            sig = re.sub(r"\s+", " ", sig)
            # Multiline signatures: append following lines until '{'
            entries.append((current_type, name, sig, " ".join(pending_doc)))
        if not line.startswith("///"):
            pending_doc = []
    return entries


def compact_signature(path: Path):
    """Better multi-line-aware signature extraction."""
    text = path.read_text()
    results = []
    current_type = None
    doc: list[str] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        # Trait impls (`impl Styled for X`) attribute to the target type X so
        # a following free fn isn't credited to the trait (e.g. "Styled").
        m = re.match(r"impl (?:\w+ for )?(\w+)\s*\{?", line)
        if m and not line.startswith("impl<"):
            current_type = m.group(1)
            doc = []
            i += 1
            continue
        if line.startswith("///"):
            doc.append(line[3:].strip())
            i += 1
            continue
        m = re.match(r"pub(?:\(crate\))? fn (\w+)", line)
        if m and current_type:
            sig_lines = [line]
            while "{" not in sig_lines[-1] and i + 1 < len(lines):
                i += 1
                sig_lines.append(lines[i].strip())
            sig = " ".join(sig_lines)
            sig = sig.split("{")[0].strip()
            sig = re.sub(r"\s+", " ", sig)
            results.append((current_type, m.group(1), sig, " ".join(doc)))
            doc = []
        elif not line.startswith("///"):
            doc = []
        i += 1
    return results


def extract_previews():
    """{preview_fn_name: dedented_body} from storybook.rs."""
    text = STORYBOOK.read_text()
    previews = {}
    for m in re.finditer(r"    fn (\w+_preview)\([^)]*\)[^{]*\{\n", text):
        name = m.group(1)
        start = m.end()
        depth = 1
        i = start
        while depth > 0 and i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        body = text[start : i - 1]
        # Dedent by the 8-space fn-body indent.
        lines = [l[8:] if l.startswith(" " * 8) else l for l in body.splitlines()]
        previews[name] = "\n".join(lines).strip("\n")
    return previews


def main():
    previews = extract_previews()
    out = [
        "//! GENERATED by scripts/gen-docs.py — do not edit by hand.",
        "//! API reference + usage snippets rendered by the storybook docs pages.",
        "",
        "pub struct ApiEntry {",
        "    pub type_name: &'static str,",
        "    pub signature: &'static str,",
        "    pub doc: &'static str,",
        "}",
        "",
        "pub struct ComponentDocs {",
        "    pub module: &'static str,",
        "    pub source_path: &'static str,",
        "    pub usage: &'static str,",
        "    pub api: &'static [ApiEntry],",
        "}",
        "",
    ]

    lookup = []
    for path in sorted(COMPONENTS.glob("*.rs")):
        module = path.stem
        if module == "mod":
            continue
        api = compact_signature(path)
        const = module.upper()
        out.append(f"pub static {const}_API: &[ApiEntry] = &[")
        for type_name, _fn_name, sig, doc in api:
            sig_esc = sig.replace("\\", "\\\\").replace('"', '\\"')
            doc_esc = doc.replace("\\", "\\\\").replace('"', '\\"')
            out.append(
                f'    ApiEntry {{ type_name: "{type_name}", signature: "{sig_esc}", doc: "{doc_esc}" }},'
            )
        out.append("];")
        out.append("")

        preview = previews.get(f"{module}_preview", "")
        usage_esc = preview.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        out.append(f'pub static {const}_USAGE: &str = "{usage_esc}";')
        out.append("")
        lookup.append((module, const))

    out.append("/// Docs lookup by component module name.")
    out.append("pub static COMPONENT_DOCS: &[ComponentDocs] = &[")
    for module, const in lookup:
        out.append(
            f'    ComponentDocs {{ module: "{module}", source_path: "src/components/{module}.rs", usage: {const}_USAGE, api: {const}_API }},'
        )
    out.append("];")
    out.append("")
    out.append("pub fn docs_for(module: &str) -> Option<&'static ComponentDocs> {")
    out.append("    COMPONENT_DOCS.iter().find(|docs| docs.module == module)")
    out.append("}")
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(lookup)} components)")


if __name__ == "__main__":
    main()
