//! Cargo.toml dependency injection and hello-world `main.rs` detection.

use anyhow::{Context, Result};
use std::path::Path;
use toml_edit::{DocumentMut, Item, Table, Value};

use crate::registry::{CrateDep, GitDep};

/// True when `main.rs` is still the untouched `cargo new` hello-world
/// (`fn main() { println!("Hello, world!"); }` modulo whitespace/comments).
pub fn is_hello_world_main(source: &str) -> bool {
    let stripped = strip_rs_trivia(source);
    matches!(
        stripped.as_str(),
        "fnmain(){println!(\"Hello, world!\");}"
            | "fnmain(){println!(\"Hello, world!\")}"
            | "pubfnmain(){println!(\"Hello, world!\");}"
            | "pubfnmain(){println!(\"Hello, world!\")}"
    )
}

/// Strip line/block comments and all whitespace for hello-world comparison.
fn strip_rs_trivia(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    let bytes = source.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        // line comment
        if bytes[i] == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            i += 2;
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        // block comment
        if bytes[i] == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'*' {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            i = (i + 2).min(bytes.len());
            continue;
        }
        // string literal — keep contents so we can match the println payload
        if bytes[i] == b'"' {
            out.push('"');
            i += 1;
            while i < bytes.len() {
                let c = bytes[i] as char;
                out.push(c);
                i += 1;
                if c == '\\' && i < bytes.len() {
                    out.push(bytes[i] as char);
                    i += 1;
                    continue;
                }
                if c == '"' {
                    break;
                }
            }
            continue;
        }
        let c = bytes[i] as char;
        if !c.is_whitespace() {
            out.push(c);
        }
        i += 1;
    }
    out
}

/// Minimal runnable gpui app scaffold written when `main.rs` is still hello-world.
pub fn scaffold_main_rs() -> &'static str {
    r#"//! Generated by `rcn init` — a minimal gpui app using the vendored Theme.

// Vendored rcn modules; dead_code allowed until your app uses them all.
#[allow(dead_code)]
mod assets;
#[allow(dead_code)]
mod components;
#[allow(dead_code)]
mod motion;
#[allow(dead_code)]
mod theme;

use gpui::{
    div, px, size, App, AppContext, Application, Bounds, Context, IntoElement,
    ParentElement, Render, Styled, Window, WindowBounds, WindowOptions,
};
use theme::Theme;

fn main() {
    // At this gpui rev the platform lives in the gpui_platform crate.
    let platform = gpui_platform::current_platform(false);
    let app = Application::with_platform(platform);
    app.run(|cx: &mut App| {
        cx.set_global(Theme::light());
        let bounds = Bounds::centered(None, size(px(480.0), px(320.0)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                titlebar: Some(gpui::TitlebarOptions {
                    title: Some("rcn".into()),
                    ..Default::default()
                }),
                ..Default::default()
            },
            |_window, cx| cx.new(|_| Ready),
        )
        .expect("failed to open window");
        cx.activate(true);
    });
}

struct Ready;

impl Render for Ready {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let theme = Theme::of(cx);
        div()
            .flex()
            .items_center()
            .justify_center()
            .size_full()
            .bg(theme.background)
            .text_color(theme.foreground)
            .child("rcn is ready")
    }
}
"#
}

/// Module lines a customized binary crate should add manually.
pub fn suggested_mod_lines() -> &'static str {
    "#[allow(dead_code)]\nmod assets;\n#[allow(dead_code)]\nmod components;\n#[allow(dead_code)]\nmod motion;\n#[allow(dead_code)]\nmod theme;"
}

/// Ensure `[dependencies]` contains each git dep (skip if the key already exists).
/// Returns the names that were newly inserted.
pub fn ensure_git_deps(
    cargo_toml: &str,
    deps: &[(String, GitDep)],
) -> Result<(String, Vec<String>)> {
    let mut doc = cargo_toml
        .parse::<DocumentMut>()
        .context("failed to parse Cargo.toml")?;
    let table = dependencies_table_mut(&mut doc)?;
    let mut added = Vec::new();
    for (name, dep) in deps {
        if table.contains_key(name) {
            continue;
        }
        let mut inline = toml_edit::InlineTable::new();
        inline.insert("git", Value::from(dep.git.as_str()));
        if !dep.rev.is_empty() {
            inline.insert("rev", Value::from(dep.rev.as_str()));
        }
        // Only emit package= when it differs from the dependency key.
        if !dep.package.is_empty() && dep.package != *name {
            inline.insert("package", Value::from(dep.package.as_str()));
        }
        if !dep.features.is_empty() {
            let mut arr = toml_edit::Array::new();
            for f in &dep.features {
                arr.push(f.as_str());
            }
            inline.insert("features", Value::Array(arr));
        }
        table.insert(name, Item::Value(Value::InlineTable(inline)));
        added.push(name.clone());
    }
    Ok((doc.to_string(), added))
}

/// Ensure `[dependencies]` contains each crates.io dep (skip if present).
/// Returns the names that were newly inserted.
pub fn ensure_crate_deps(
    cargo_toml: &str,
    deps: &[CrateDep],
) -> Result<(String, Vec<String>)> {
    let mut doc = cargo_toml
        .parse::<DocumentMut>()
        .context("failed to parse Cargo.toml")?;
    let table = dependencies_table_mut(&mut doc)?;
    let mut added = Vec::new();
    for dep in deps {
        if table.contains_key(&dep.name) {
            continue;
        }
        table.insert(&dep.name, Item::Value(Value::from(dep.version.as_str())));
        added.push(dep.name.clone());
    }
    Ok((doc.to_string(), added))
}

fn dependencies_table_mut(doc: &mut DocumentMut) -> Result<&mut Table> {
    if doc.get("dependencies").is_none() {
        doc["dependencies"] = Item::Table(Table::new());
    }
    doc["dependencies"]
        .as_table_mut()
        .ok_or_else(|| anyhow::anyhow!("[dependencies] is not a table"))
}

/// Read, transform, and write a consumer Cargo.toml in place.
pub fn update_cargo_toml(path: &Path, f: impl FnOnce(&str) -> Result<String>) -> Result<()> {
    let original = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let next = f(&original)?;
    if next != original {
        std::fs::write(path, next)
            .with_context(|| format!("failed to write {}", path.display()))?;
    }
    Ok(())
}

/// Apply git deps from a registry map onto a Cargo.toml string.
pub fn inject_gpui_deps(
    cargo_toml: &str,
    gpui_deps: &std::collections::BTreeMap<String, GitDep>,
) -> Result<(String, Vec<String>)> {
    let pairs: Vec<(String, GitDep)> = gpui_deps
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    ensure_git_deps(cargo_toml, &pairs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::GitDep;
    use std::collections::BTreeMap;

    #[test]
    fn detects_hello_world_variants() {
        assert!(is_hello_world_main(r#"fn main() { println!("Hello, world!"); }"#));
        assert!(is_hello_world_main(
            r#"
            // comment
            fn main() {
                println!("Hello, world!");
            }
            "#
        ));
        assert!(!is_hello_world_main(
            r#"fn main() { println!("something else"); }"#
        ));
        assert!(!is_hello_world_main(
            r#"fn main() { println!("Hello, world!"); do_more(); }"#
        ));
    }

    #[test]
    fn injects_git_deps_preserving_existing() {
        let original = r#"[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1"
"#;
        let mut gpui = BTreeMap::new();
        gpui.insert(
            "gpui".into(),
            GitDep {
                git: "https://github.com/zed-industries/zed".into(),
                rev: "abc".into(),
                package: "gpui".into(),
                features: vec![],
            },
        );
        gpui.insert(
            "gpui_platform".into(),
            GitDep {
                git: "https://github.com/zed-industries/zed".into(),
                rev: "abc".into(),
                package: "gpui_platform".into(),
                features: vec!["font-kit".into()],
            },
        );
        let (next, added) = inject_gpui_deps(original, &gpui).unwrap();
        assert_eq!(added, vec!["gpui".to_string(), "gpui_platform".to_string()]);
        assert!(next.contains("serde = \"1\""));
        assert!(next.contains("gpui"));
        assert!(next.contains("rev = \"abc\""));
        assert!(next.contains("font-kit"));
        // second pass is idempotent
        let (again, added2) = inject_gpui_deps(&next, &gpui).unwrap();
        assert!(added2.is_empty());
        assert_eq!(again, next);
    }

    #[test]
    fn skips_existing_crate_deps() {
        let original = r#"[package]
name = "demo"
version = "0.1.0"

[dependencies]
unicode-segmentation = "1"
"#;
        let deps = vec![
            CrateDep {
                name: "unicode-segmentation".into(),
                version: "1".into(),
            },
            CrateDep {
                name: "anyhow".into(),
                version: "1".into(),
            },
        ];
        let (next, added) = ensure_crate_deps(original, &deps).unwrap();
        assert_eq!(added, vec!["anyhow".to_string()]);
        assert!(next.contains("unicode-segmentation = \"1\""));
        assert!(next.contains("anyhow = \"1\""));
    }

    #[test]
    fn errors_on_bad_toml() {
        let err = ensure_crate_deps("[[[not toml", &[]).unwrap_err().to_string();
        assert!(err.contains("parse"), "{err}");
    }
}
