//! `components/mod.rs` insertion helpers.

use anyhow::{Context, Result};
use std::path::Path;

/// Header written by `rcn init` before any `pub mod` lines exist.
pub const COMPONENTS_MOD_HEADER: &str = "\
// Generated by rcn. Component modules are added by `rcn add`.
// Do not delete this file — `rcn add` inserts `pub mod` lines below.
";

/// Ensure `pub mod <module>;` lines exist in `mod.rs` contents.
/// Keeps the list sorted and deduplicated. Preserves a leading comment block.
/// Returns the new file text and whether it changed.
pub fn ensure_pub_mods(contents: &str, modules: &[String]) -> (String, bool) {
    let mut existing: Vec<String> = Vec::new();
    let mut header_lines: Vec<&str> = Vec::new();
    let mut saw_mod = false;

    for line in contents.lines() {
        let trimmed = line.trim();
        if let Some(name) = parse_pub_mod(trimmed) {
            saw_mod = true;
            if !existing.iter().any(|m| m == &name) {
                existing.push(name);
            }
        } else if !saw_mod {
            // Keep preamble (comments / blank lines) before the first pub mod.
            header_lines.push(line);
        } else if trimmed.is_empty() || trimmed.starts_with("//") || trimmed.starts_with("/*") {
            // Trailing comments after mods are dropped; we regenerate a clean list.
            continue;
        } else {
            // Unknown content after mods — keep it in the header bucket only if
            // we haven't started mods; otherwise ignore to avoid duplication.
            continue;
        }
    }

    for m in modules {
        if !existing.iter().any(|e| e == m) {
            existing.push(m.clone());
        }
    }
    existing.sort();
    existing.dedup();

    let mut out = String::new();
    // Trim trailing blank lines from header, then ensure one blank line before mods.
    while header_lines
        .last()
        .is_some_and(|l| l.trim().is_empty())
    {
        header_lines.pop();
    }
    if header_lines.is_empty() {
        out.push_str(COMPONENTS_MOD_HEADER);
        if !COMPONENTS_MOD_HEADER.ends_with('\n') {
            out.push('\n');
        }
    } else {
        for line in &header_lines {
            out.push_str(line);
            out.push('\n');
        }
    }
    if !existing.is_empty() {
        if !out.ends_with('\n') {
            out.push('\n');
        }
        // blank line between header and mods when header has content
        if out
            .lines()
            .last()
            .is_some_and(|l| !l.trim().is_empty())
        {
            out.push('\n');
        }
        for m in &existing {
            out.push_str("pub mod ");
            out.push_str(m);
            out.push_str(";\n");
        }
    }

    // Normalize: if contents lacked trailing newline comparison still works.
    let changed = out != contents;
    (out, changed)
}

fn parse_pub_mod(trimmed: &str) -> Option<String> {
    let rest = trimmed.strip_prefix("pub mod ")?;
    let name = rest.strip_suffix(';')?.trim();
    if name.is_empty() || name.contains(char::is_whitespace) {
        return None;
    }
    Some(name.to_string())
}

/// Read-or-create `mod_path`, insert modules, write back. Returns whether changed.
pub fn update_components_mod(mod_path: &Path, modules: &[String]) -> Result<bool> {
    let current = if mod_path.exists() {
        std::fs::read_to_string(mod_path)
            .with_context(|| format!("failed to read {}", mod_path.display()))?
    } else {
        if let Some(parent) = mod_path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("failed to create {}", parent.display()))?;
        }
        COMPONENTS_MOD_HEADER.to_string()
    };
    let (next, changed) = ensure_pub_mods(&current, modules);
    if changed {
        std::fs::write(mod_path, next)
            .with_context(|| format!("failed to write {}", mod_path.display()))?;
    }
    Ok(changed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inserts_sorted_and_dedup() {
        let (out, changed) = ensure_pub_mods(
            COMPONENTS_MOD_HEADER,
            &["button".into(), "alert".into(), "button".into()],
        );
        assert!(changed);
        assert!(out.contains("pub mod alert;\n"));
        assert!(out.contains("pub mod button;\n"));
        let alert = out.find("pub mod alert;").unwrap();
        let button = out.find("pub mod button;").unwrap();
        assert!(alert < button);
        // idempotent
        let (out2, changed2) = ensure_pub_mods(&out, &["button".into()]);
        assert!(!changed2);
        assert_eq!(out2, out);
    }

    #[test]
    fn preserves_header_comment() {
        let src = "// keep me\n\npub mod zebra;\n";
        let (out, _) = ensure_pub_mods(src, &["apple".into()]);
        assert!(out.starts_with("// keep me\n"));
        assert!(out.contains("pub mod apple;\n"));
        assert!(out.contains("pub mod zebra;\n"));
        let apple = out.find("pub mod apple;").unwrap();
        let zebra = out.find("pub mod zebra;").unwrap();
        assert!(apple < zebra);
    }
}
